### ISSUE TITLE
Concurrency limits issue in PulsarClient

### ISSUE THREAD

**Issue by RobertIndie** [fsharplang-ru/pulsar-client-dotnet#158] opened 2021-04-07 02:52 UTC
Here we did two tests. 
ProduceConcurrent: Use 100 producers to produce data concurrently to a topic, and then record the latency for each sends operation. 
ConsumeProduceConcurrent: Runs a loop of synchronous Consumer.ReceiveAsync and asynchronous Producer.SendAsync operations with 100 producers, and then record the latency in the same way.
In the above tests, we use a single PulsarClient to create all producers and consumers.

Then we draw the Latecny by Percentile Distribution for these two tests as shown below.
![image](https://user-images.githubusercontent.com/16974619/113803069-5f99d780-978e-11eb-98ff-2b33eb253fb7.png)
In above picture `cp*.hgrm` represents the result of test `ConsumeProduceConcurrent` while `produce*.hgrm` represents the result of test `ProduceConcurrent`.

But when we create pulsar clients separately for each producer and consumer, the result of tests change to the following:
![image](https://user-images.githubusercontent.com/16974619/113803378-fd8da200-978e-11eb-93d5-308c5b34c142.png)
There is a significant reduction in latency in the test `ConsumeProduceConcurrent`. As more clients are used, the latency is reduced. Is it because there are some concurrency limitations inside the PulsarClient?

**Comment by Lanayx** [comment] 2021-04-07 08:20
Can you please add the code for both tests? (ideally with the ability for me to get those results) There are several things that don't make sense to me - how can ConsumerProduce have lower latency than just Produce, what is the difference between produce1 and produce2, cc_cp1 and cc_cp2, also you wrote the more clients are used the lower is the latency although logically it should be opposite.

**Comment by Lanayx** [comment] 2022-01-05 07:01
@RobertIndie I've just reread the description and understood that I misread it in the first place. The architecture of PulsarClient is that it should be used as a singleton, this allows the shorcuts such as [static logger](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/src/Pulsar.Client/Common/Log.fs#L9)

**Comment by Lanayx** [comment] 2022-05-04 07:47
Closing as by design

**Closed as completed by Lanayx** 2022-05-04 07:47 UTC
Labels: needs more details
