### ISSUE TITLE
DateTime not supported in schema

### ISSUE THREAD

**Issue by RobertIndie** [fsharplang-ru/pulsar-client-dotnet#154] opened 2021-03-16 07:05 UTC
When I use a DateTime type field in the schema, it throws an Expcetion `System.ArgumentException: DateTime not supported`

Sample c# code:
```csharp
class MessageDate
{
    public DateTime CreatedTime { get; set; }
}

[Fact]
public async Task SendMsg()
{
    var producer = await Client.NewProducer(Schema.JSON<MessageDate>())
        .Topic("schema")
        .CreateAsync();
    var consumer = await Client.NewConsumer(Schema.JSON<MessageDate>())
        .Topic("schema")
        .SubscriptionName("my-sub")
        .SubscribeAsync();

    var msg = new MessageDate {CreatedTime = DateTime.Today};
    await producer.SendAsync(msg);

    var cmsg = await consumer.ReceiveAsync();
    var value = cmsg.GetValue();
    Log.WriteLine(value.ToString());
}
```

Is it that DateTime cannot be used here? What is the best practice?

**Comment by Lanayx** [comment] 2021-03-16 07:42
Hi, @RobertIndie! Can you please provide the full stacktrace in case of exception next time. Here it is
```
System.ArgumentException: DateTime not supported
   at AvroSchemaGenerator.GenerateSchema.ToAvroDataType(String type)
   at AvroSchemaGenerator.GenerateSchema.GetField(PropertyInfo p)
   at AvroSchemaGenerator.GenerateSchema.AddFields(PropertyInfo p, Dictionary`2 finalSchema)
   at AvroSchemaGenerator.GenerateSchema.PropertyInfo(PropertyInfo property, Dictionary`2 finalSchema)
   at AvroSchemaGenerator.GenerateSchema.GetSchema(Type type)
```
As you can see, the exception happens in AvroSchemaGenerator library, can you please create an issue [in it's repo](https://github.com/eaba/AvroSchemaGenerator)

**Comment by RobertIndie** [comment] 2021-03-16 08:17
Thank you. I have created an issue: https://github.com/eaba/AvroSchemaGenerator/issues/9

**Comment by Lanayx** [comment] 2021-03-16 09:51
A workaround will be not to use DateTime type in DTO. For example in Avro .net library logical types are not supported at all.

**Comment by eaba** [comment] 2021-04-12 16:17
@RobertIndie @Lanayx released fix https://www.nuget.org/packages/AvroSchemaGenerator/1.9.0-beta.2

Logical Types are supported when using `SpecificDatumReader` , `SpecificDatumWriter` and not supported in `ReflectReader`,  `ReflectWriter`

**Comment by Lanayx** [comment] 2021-04-12 18:11
@eaba Thank you, can you please give an example of how to use it?

**Comment by eaba** [comment] 2021-04-12 18:23
@Lanayx https://github.com/eaba/AvroSchemaGenerator/blob/dev/AvroSchemaGenerator.Tests/LogicalTypeTests.cs

**Comment by Lanayx** [comment] 2021-04-12 18:43
Hmm.. Still not getting - how to use it use it in regular case - when defining a dto like in the initial thread message.

**Comment by eaba** [comment] 2021-04-12 18:57
The DTO must implement `ISpecificRecord` like below:
````csharp
public class MessageDate: ISpecificRecord
    {
        public DateTime CreatedTime { get; set; }
        public AvroDecimal Size { get; set; }
        public string DayOfWeek { get; set; }

        [Ignore]
        public Schema Schema { get; set; }

        public object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return CreatedTime;
                case 1: return Size;
                case 2: return DayOfWeek;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }

        public void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: CreatedTime = (DateTime)fieldValue; break;
                case 1: Size = (AvroDecimal)fieldValue; break;
                case 2: DayOfWeek = (System.String)fieldValue; break;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
````

**Comment by Lanayx** [comment] 2021-04-12 19:09
I don't think it's a right approach, the schema type is json, so there shouldn't be any dependecy on avro library. We are only interested in schema generation, serialisation is out of scope for this issue.

**Comment by eaba** [comment] 2021-04-12 19:14
Probably you used `AvroSchemaGenerator` under the hood to generate schema for JSON - in that case user does not need to worry but when using Avro the DTO must implement `ISpecificRecord` for now until Avro has support for `LogicalTypes` everywhere.

**Comment by eaba** [comment] 2021-04-12 19:18
````csharp
public class MessageDate
    {
        public DateTime CreatedTime { get; set; }
        public AvroDecimal Size { get; set; }
        public string DayOfWeek { get; set; }
    }
````

**Comment by Lanayx** [comment] 2021-04-12 19:19
Thank you for the clarification, I'll give it a try

**Comment by RobertIndie** [comment] 2021-04-13 03:19
Thank @eaba . But it seems to be too complicated for users to use. Can we implement it like https://github.com/eaba/AvroSchemaGenerator/issues/9#issuecomment-800098319 ?
```csharp
class MessageDate
{
    [LogicalType(LogicalTypeKind.Date)]
    public DateTime CreatedTime { get; set; }
}
```

**Comment by eaba** [comment] 2021-04-13 03:56
> Thank @eaba . But it seems to be too complicated for users to use. Can we implement it like [eaba/AvroSchemaGenerator#9 (comment)](https://github.com/eaba/AvroSchemaGenerator/issues/9#issuecomment-800098319) ?
> 
> ```cs
> class MessageDate
> {
>     [LogicalType(LogicalTypeKind.Date)]
>     public DateTime CreatedTime { get; set; }
> }
> ```

The library takes care of this automatically without the user having to use attribute - which is even more simpler. 

What part of it is complicated? The DateTime field or the `ISpecificRecord`?

**Comment by Lanayx** [comment] 2021-04-13 08:17
@eaba there is something wrong with the new nuget package, can you please have a look? Maybe a regular version is needed, not beta. I'm getting an exception 
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'AvroSchemaGenerator, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assemb
ly reference. (0x80131040)
```
Looking at the assembly properties, it seems to be wrong (version 1.0.0.0)
![image](https://user-images.githubusercontent.com/3329606/114520064-b51c2b80-9c49-11eb-95f3-b4858c638cab.png)

compare with
![image](https://user-images.githubusercontent.com/3329606/114519964-99188a00-9c49-11eb-80ea-c8cfc6f00cfd.png)

**Comment by eaba** [comment] 2021-04-13 11:21
You may need to update `AvroSchemaGenerator` everywhere
This happens when one of your dependence hold reference to another version....

If the fix is confirmed to work then I will release a proper version

**Comment by Lanayx** [comment] 2021-04-13 12:21
Yes, I know about dependencies, the issue is that you didn't specify the assembly version when pushing library to Nuget, can you please fix it?

**Comment by Lanayx** [comment] 2021-04-13 14:24
@eaba just checked 1.9.0-beta.5 and it works. However without additional attribute it will always default to logical "Date" type, I still think that adding additional attribute will be beneficial so end user can decide whether he wants "Date" or "Timestamp" or any other logical type avro schema supports. Moreover user might want to have the actual type being int64 while having logical type as Timestamp

**Comment by eaba** [comment] 2021-04-13 14:46
> 
> 
> @eaba just checked 1.9.0-beta.5 and it works. However without additional attribute it will always default to logical "Date" type, I still think that adding additional attribute will be beneficial so end user can decide whether he wants "Date" or "Timestamp" or any other logical type avro schema supports. Moreover user might want to have the actual type being int64 while having logical type as Timestamp

That will depend on Avro c#, I will check that out.

**Comment by eaba** [comment] 2021-04-13 14:52
Checked. I will work on that

**Comment by Lanayx** [comment] 2021-04-13 15:26
> 
> 
> > @eaba just checked 1.9.0-beta.5 and it works. However without additional attribute it will always default to logical "Date" type, I still think that adding additional attribute will be beneficial so end user can decide whether he wants "Date" or "Timestamp" or any other logical type avro schema supports. Moreover user might want to have the actual type being int64 while having logical type as Timestamp
> 
> That will depend on Avro c#, I will check that out.

I think it shouldn't depend on Avro, the attribute should only exist in AvroGenerator library, it's only purpose is to generate additional `"logicalType": "date"` line in schema definition.

**Comment by eaba** [comment] 2021-04-13 15:41
> 
> 
> > > @eaba just checked 1.9.0-beta.5 and it works. However without additional attribute it will always default to logical "Date" type, I still think that adding additional attribute will be beneficial so end user can decide whether he wants "Date" or "Timestamp" or any other logical type avro schema supports. Moreover user might want to have the actual type being int64 while having logical type as Timestamp
> > 
> > 
> > That will depend on Avro c#, I will check that out.
> 
> I think it shouldn't depend on Avro, the attribute should only exist in AvroGenerator library, it's only purpose is to generate additional `"logicalType": "date"` line in schema definition.

Yeah....just checked to make sure it is implemented

**Comment by eaba** [comment] 2021-04-13 17:50
@Lanayx Implemented in the latest package

````csharp
public class MessageTimeKind
    {
        [LogicalType(LogicalTypeKind.TimeMicrosecond)]
        public TimeSpan TimeMicros { get; set; }

        [LogicalType(LogicalTypeKind.TimeMillisecond)]
        public TimeSpan TimeMillis { get; set; }
    }
	
    public class MessageTimestampKind
    {
        [LogicalType(LogicalTypeKind.TimestampMicrosecond)]
        public DateTime StampMicros { get; set; }

        [LogicalType(LogicalTypeKind.TimestampMillisecond)]
        public DateTime StampMillis { get; set; }
    }
	
    public class MessageDateKind
    {
        [LogicalType(LogicalTypeKind.Date)]
        public DateTime CreatedTime { get; set; }
        public AvroDecimal Size { get; set; }
        public string DayOfWeek { get; set; }
    }
````

**Comment by Lanayx** [comment] 2021-04-13 21:11
Great! Will have a look tomorrow

**Comment by Lanayx** [comment] 2021-04-14 10:04
@eaba I did few tries and got the following exception
```
Unhandled exception. System.Exception: Unknown LogicalTypeKind:TimeMillisecond
   at AvroSchemaGenerator.GenerateSchema.ToAvroDataType(String type, Nullable`1 kind)
```

**Comment by eaba** [comment] 2021-04-14 11:06
`TimeMillisecond` can only be used on `TimeSpan`
```csharp
public class MessageTimeKind
    {
        [LogicalType(LogicalTypeKind.TimeMicrosecond)]
        public TimeSpan TimeMicros { get; set; }

        [LogicalType(LogicalTypeKind.TimeMillisecond)]
        public TimeSpan TimeMillis { get; set; }
    }
```

**Comment by Lanayx** [comment] 2021-04-14 12:05
@eaba Ok, I think we are good to go with that :)

**Closed as completed** 2021-04-14 16:24 UTC
Labels: question

**Comment by fadelle** [comment] 2023-09-16 09:19
> I don't think it's a right approach, the schema type is json, so there shouldn't be any dependecy on avro library. We are only interested in schema generation, serialisation is out of scope for this issue.

i am using Schema.JSON<T>() but also getting the error below 

System.ArgumentException
  HResult=0x80070057
  Message=String[] not supported
  Source=AvroSchemaGenerator
  StackTrace:
   at AvroSchemaGenerator.GenerateSchema.ToAvroDataType(String type, Nullable`1 kind) in AvroSchemaGenerator\GenerateSchema.cs:line 1797
   at AvroSchemaGenerator.GenerateSchema.GetField(PropertyInfo p) in AvroSchemaGenerator\GenerateSchema.cs:line 819
   at AvroSchemaGenerator.GenerateSchema.GetUserDefinedProperties(PropertyInfo property, Dictionary`2 finalSchema, List`1 existingTypes) in AvroSchemaGenerator\GenerateSchema.cs:line 1113
   at AvroSchemaGenerator.GenerateSchema.PropertyInfo(PropertyInfo property, Dictionary`2 finalSchema, List`1 existingTypes) in AvroSchemaGenerator\GenerateSchema.cs:line 153
   at AvroSchemaGenerator.GenerateSchema.GetSchemaObject(Type type) in AvroSchemaGenerator\GenerateSchema.cs:line 80
   at Pulsar.Client.Schema.JsonSchema`1..ctor()
   at Pulsar.Client.Api.Schema.JSON[T]()
   at ApachePulsar.Business.Entities.ConfigBase.GetSchema[T]()
   at ApachePulsar.Broker.Managers.PulsarConsumerManager.<CreateConsumer>d__2`1.MoveNext()
   at ApachePulsar.Broker.Handlers.PulsarHandler`1.<Subscribe>d__5.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

i am not using avro at all but i am getting these errors

**Comment by Lanayx** [comment] 2023-09-16 14:46
@fadelle This is the implementation detail taken from Java client: avro, json and protobuf options all use avro schema, only serialisation is different. Protobuf-native uses protobuf schema

**Comment by fadelle** [comment] 2023-09-26 11:55
Thank you @Lanayx , but what if i want to send raw json without being restricted to a schema ?

**Comment by Lanayx** [comment] 2023-09-26 14:27
@fadelle then you just don't use any schema, send bytes and do serialisation in your code
