### ISSUE TITLE
IReader.HasMessageAvailableAsync incorrectly returns false when MessageIdInclusive=true

### ISSUE THREAD

**Issue by TjeuKayim** [fsharplang-ru/pulsar-client-dotnet#134] opened 2020-12-15 10:21 UTC
`HasMessageAvailableAsync` as it always returns false for the last message only when `StartMessageIdInclusive(true)` is configured. This seems like a bug.

Is it expected that the C# test case below fails on the last assertion?

```cs
private async Task MessageIdInclusive_HasMessageAvailableAsync(string topic, PulsarClient client)
{
    await using var producer = await client.NewProducer().Topic(topic).CreateAsync();
    var previousMessageId = await producer.SendAsync(new byte[] { 1 });
    var expectedMessageId = await producer.SendAsync(new byte[] { 2 });

    // MessageId Exclusive works as expected
    await using var exclusiveReader = await client.NewReader().Topic(topic)
        .StartMessageId(previousMessageId).StartMessageIdInclusive(false).CreateAsync();
    var available = await exclusiveReader.HasMessageAvailableAsync();
    var actual = await exclusiveReader.ReadNextAsync();
    AssertEqual(expectedMessageId, actual);
    Assert.True(available);

    // MessageId Inclusive
    await using var inclusiveReader = await client.NewReader().Topic(topic)
        .StartMessageId(expectedMessageId).StartMessageIdInclusive(true).CreateAsync();
    available = await inclusiveReader.HasMessageAvailableAsync();
    actual = await inclusiveReader.ReadNextAsync();
    AssertEqual(expectedMessageId, actual);
    Assert.True(available); // <===== this assertion fails while a message was available??
}
```

The problem seems to be at line https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/d80640ea82410479f60ff23f1e3b7f0d9554202c/src/Pulsar.Client/Internal/ConsumerImpl.fs#L132

When debugging my test case `lastMessageIdInBroker` and `lastDequeuedMessageId` are equal except for the Type, respectively `Individual` and `Cumulative(0,null)`.
So my test case passes if I modify `MessageId.CompareTo` and ignore the Type when comparing.
I have no experience with the code base, so this is probably not a proper solution.

**Comment by Lanayx** [comment] 2020-12-15 12:00
Hi, @TjeuKayim, which pulsar server version are you using? This sounds similar to https://github.com/apache/pulsar/issues/6333

**Comment by TjeuKayim** [comment] 2020-12-15 12:06
Thanks for the quick response.
The Pulsar broker version is 2.7.0.

**Comment by TjeuKayim** [comment] 2020-12-15 12:13
Maybe the comparison between batch MessageId and non-batch MessageId is not up to date with the Java equivalent https://github.com/apache/pulsar/blob/cb6617fa02d235f341026adf43fee87627a20c8b/pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageIdImpl.java#L70-L84

**Comment by Lanayx** [comment] 2020-12-15 12:19
Thanks, I'll have a look tomorrow. In a while you can create a failing test in this file https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/tests/IntegrationTests/Reader.fs and send a PR to merge

**Comment by Lanayx** [comment] 2020-12-17 09:24
@TjeuKayim Hi, I've just found out that the behavior in Java client (2.6.2) is the same. Can you please create an issue in Pulsar repo and link it here? This is the test that I've made:
![image](https://user-images.githubusercontent.com/3329606/102468567-bbffac80-4062-11eb-94a0-59b694a9ddad.png)

**Comment by TjeuKayim** [comment] 2020-12-17 11:03
That's unexpected, it's also a bug in the Java client. I will create an issue in the `apache/pulsar` repo if I have time next week.

**Comment by Lanayx** [comment] 2020-12-17 11:08
I'd better want this to be fixed on broker side, since _getLastMessageIdAsync_ method returns non-batched messageId, therefore the comparison fails. Expected behavior would be to receive a real batched messageId

**Comment by Lanayx** [comment] 2020-12-26 11:56
Seems to be fixed in 2.7.1 and 2.8 on server https://github.com/apache/pulsar/pull/8779

**Comment by TjeuKayim** [comment] 2020-12-26 12:32
Nice, I will update my Pulsar server and see if that solves the issue for me.

**Comment by TjeuKayim** [comment] 2020-12-27 14:38
With Pulsar server 2.7.0.1-rc-202012212215 the issue is indeed solved (the test that I posted in the description succeeds).
Thanks for your help!
So `MessageId.CompareTo` didn't need to change after you looked into it?

**Comment by Lanayx** [comment] 2020-12-27 15:18
You are welcome! Yes, it doesn't need to change as it conforms to the Java version.

**Closed as completed** 2020-12-27 15:51 UTC
Labels: bug
